<a href="https://colab.research.google.com/github/shubham-7745/PDS-Assignment/blob/main/practical_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Name:-  Shubham Suresh Matsagar
Roll number :-05
Class:- Sy - B-AI&DS

In [ ]:
Practical 4

Aim :- Numerical Computation with NumPy: Perform different computations using
 NumPy library.


Theroy

### 1. Explain the role of NumPy in the Python scientific computing ecosystem.

NumPy (Numerical Python) is the foundational library for numerical computing in Python. Its primary role is to provide a high-performance multidimensional array object, called `ndarray`, and tools for working with these arrays. It serves as the backbone for many other scientific computing libraries in Python, including:

*   **Efficient Data Storage and Manipulation:** It allows for storing and operating on large datasets efficiently.
*   **Mathematical Operations:** It provides a vast collection of mathematical functions to operate on arrays, including linear algebra routines, Fourier transforms, and random number capabilities.
*   **Interoperability:** It acts as the standard data exchange format for numerical data between different scientific Python libraries.

### 2. Why is NumPy considered faster than pure Python computations?

NumPy's speed advantage over pure Python computations stems from several key factors:

*   **Vectorization:** NumPy operations are often *vectorized*, meaning they operate on entire arrays at once, rather than element by element in Python loops. This eliminates the overhead of Python's interpreter for each individual operation.
*   **C Implementation:** The core of NumPy, especially its `ndarray` object and many of its functions, are implemented in C and Fortran. This allows NumPy to perform computations at speeds comparable to compiled languages.
*   **Memory Efficiency:** NumPy arrays are homogeneous (all elements are of the same data type) and stored in contiguous blocks of memory. This leads to better cache utilization and reduces memory overhead compared to Python lists, which are arrays of pointers to Python objects scattered in memory.
*   **Optimized Algorithms:** NumPy utilizes highly optimized algorithms for common numerical tasks.

### 3. What types of mathematical operations can be performed using NumPy?

NumPy supports a wide array of mathematical operations, categorized as follows:

*   **Basic Arithmetic Operations:** Addition, subtraction, multiplication (element-wise), division, modulo, exponentiation.
*   **Linear Algebra:** Dot product, matrix multiplication, inverse, determinant, eigenvalues, eigenvectors, solving linear equations, singular value decomposition (SVD).
*   **Mathematical Functions:** Trigonometric (sin, cos, tan), exponential (exp, log), hyperbolic, square root, absolute value, rounding, ceiling, floor.
*   **Statistical Operations:** Mean, median, standard deviation, variance, min, max, sum, product, quantiles, correlation.
*   **Random Number Generation:** Generating random numbers from various distributions (uniform, normal, etc.).
*   **Array Manipulation:** Reshaping, splitting, joining, stacking, tiling, transposing, broadcasting.
*   **Element-wise Comparisons:** Greater than, less than, equal to, etc., resulting in boolean arrays.

### 4. Explain indexing and slicing in NumPy arrays.

Indexing and slicing in NumPy arrays are powerful features that allow you to access and modify specific elements or subarrays (views) of an array, similar to Python lists but with enhanced capabilities for multidimensional arrays.

*   **Indexing:**
    *   **Basic Indexing:** Access individual elements using zero-based integer indices for each dimension. For a 1D array `arr[i]`, for a 2D array `arr[row, col]`, and so on.
    *   **Boolean Indexing:** Use a boolean array (of the same shape as the array being indexed) to select elements where the boolean array is `True`. This is very useful for filtering data based on conditions (e.g., `arr[arr > 5]`).
    *   **Fancy Indexing:** Use integer arrays or lists of integers to select non-contiguous elements or rows/columns. For example, `arr[[0, 2, 4]]` selects elements at indices 0, 2, and 4.

*   **Slicing:**
    *   Slicing allows you to extract subarrays using the syntax `start:stop:step`. The `start` index is inclusive, and the `stop` index is exclusive.
    *   **1D Slicing:** `arr[start:stop:step]` (e.g., `arr[1:5]`, `arr[::2]`).
    *   **Multidimensional Slicing:** You can slice along each dimension independently. For a 2D array: `arr[row_start:row_stop, col_start:col_stop]`. A colon `:` by itself means to select all elements along that dimension (e.g., `arr[:, 0]` selects all rows of the first column).
    *   Slices in NumPy create *views* of the original array, meaning changes to the slice will affect the original array (unless a copy is explicitly made using `.copy()`).

### 5. How does NumPy integrate with libraries like:

**a. Pandas**

Pandas is built directly on top of NumPy. Its primary data structures, `Series` (1D labeled array) and `DataFrame` (2D labeled table), internally use NumPy arrays to store data. This tight integration means:

*   **Efficient Storage:** Pandas leverages NumPy's memory efficiency and speed for numerical data.
*   **Data Conversion:** You can easily convert between Pandas Series/DataFrames and NumPy arrays using `.values` attribute or `.to_numpy()` method.
*   **Operations:** Many Pandas operations, especially numerical ones, are optimized by calling underlying NumPy functions.
*   **Missing Data:** Pandas uses NumPy's `np.nan` (Not a Number) to represent missing data, ensuring consistency in handling null values.

**b. Matplotlib**

Matplotlib, the most popular plotting library in Python, works seamlessly with NumPy arrays:

*   **Input Data:** Matplotlib functions (e.g., `plt.plot()`, `plt.scatter()`, `plt.imshow()`) readily accept NumPy arrays as input for plotting coordinates, image data, and other visual elements.
*   **Numerical Operations:** When preparing data for plotting, you often perform numerical transformations using NumPy before passing it to Matplotlib.
*   **Efficiency:** Because Matplotlib directly consumes NumPy arrays, it benefits from NumPy's efficiency, making it faster to render plots with large datasets.

**c. Scikit-learn**

Scikit-learn, the leading machine learning library in Python, fundamentally relies on NumPy arrays for its input and output data:

*   **Data Representation:** All machine learning models in Scikit-learn expect input features (`X`) and target variables (`y`) to be NumPy arrays (or array-like structures that can be converted to NumPy arrays).
*   **Model Training and Prediction:** When you call `model.fit(X, y)` or `model.predict(X)`, Scikit-learn processes these NumPy arrays efficiently.
*   **Internal Computations:** Scikit-learn algorithms themselves heavily utilize NumPy for numerical operations, matrix manipulations, and statistical calculations during model training and inference.
*   **Output Format:** Model predictions, feature importances, and other results are typically returned as NumPy arrays.

In [ ]:
import numpy as np

# Create a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])
print('1D Array:', arr_1d)

# Create a 2D NumPy array (matrix)
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
print('2D Array:\n', arr_2d)

# Get array dimensions and shape
print('Shape of 1D array:', arr_1d.shape)
print('Dimension of 1D array:', arr_1d.ndim)
print('Shape of 2D array:', arr_2d.shape)
print('Dimension of 2D array:', arr_2d.ndim)

1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]
Shape of 1D array: (5,)
Dimension of 1D array: 1
Shape of 2D array: (2, 3)
Dimension of 2D array: 2


### Basic Array Operations

In [ ]:
# Element-wise addition
arr_add = arr_1d + 10
print('Addition (arr_1d + 10):', arr_add)

# Element-wise multiplication
arr_mul = arr_1d * 2
print('Multiplication (arr_1d * 2):', arr_mul)

# Transpose a 2D array
arr_2d_T = arr_2d.T
print('Transposed 2D Array:\n', arr_2d_T)

# Dot product of two arrays (example, create another array first)
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])
dot_product = np.dot(arr_a, arr_b)
print('Dot product of arr_a and arr_b:\n', dot_product)

Addition (arr_1d + 10): [11 12 13 14 15]
Multiplication (arr_1d * 2): [ 2  4  6  8 10]
Transposed 2D Array:
 [[10 40]
 [20 50]
 [30 60]]
Dot product of arr_a and arr_b:
 [[19 22]
 [43 50]]


### Aggregation Functions

In [ ]:
# Sum of all elements in arr_1d
print('Sum of arr_1d:', np.sum(arr_1d))

# Mean of all elements in arr_2d
print('Mean of arr_2d:', np.mean(arr_2d))

# Maximum value in arr_1d
print('Max of arr_1d:', np.max(arr_1d))

# Sum along an axis in arr_2d (e.g., sum of each column)
print('Sum of columns in arr_2d:', np.sum(arr_2d, axis=0))

# Sum along an axis in arr_2d (e.g., sum of each row)
print('Sum of rows in arr_2d:', np.sum(arr_2d, axis=1))

Sum of arr_1d: 15
Mean of arr_2d: 35.0
Max of arr_1d: 5
Sum of columns in arr_2d: [50 70 90]
Sum of rows in arr_2d: [ 60 150]


### Array Manipulation (Reshaping and Broadcasting)

In [ ]:
# Reshape arr_1d into a 2x? array (NumPy infers the second dimension)
arr_1d_reshaped = arr_1d.reshape(5, 1)
print('Reshaped arr_1d (5,1):\n', arr_1d_reshaped)

# Broadcasting: Adding a 1D array to a 2D array
arr_broadcast_a = np.array([[1, 2, 3], [4, 5, 6]])
arr_broadcast_b = np.array([10, 20, 30])
arr_broadcast_result = arr_broadcast_a + arr_broadcast_b
print('Broadcasting result (arr_broadcast_a + arr_broadcast_b):\n', arr_broadcast_result)

# Another broadcasting example: adding a scalar
scalar_add_result = arr_2d + 5
print('Adding scalar to arr_2d:\n', scalar_add_result)

Reshaped arr_1d (5,1):
 [[1]
 [2]
 [3]
 [4]
 [5]]
Broadcasting result (arr_broadcast_a + arr_broadcast_b):
 [[11 22 33]
 [14 25 36]]
Adding scalar to arr_2d:
 [[15 25 35]
 [45 55 65]]


### Conclusion

In this practical, we've explored the fundamental aspects of NumPy, a powerful library for numerical computation in Python. We covered:

*   **The foundational role of NumPy** in the scientific computing ecosystem, highlighting its efficiency due to vectorization, C implementation, and memory management.
*   **Core concepts** such as the `ndarray` object, its dimensions (`ndim`), and shape (`shape`).
*   **Basic array operations**, including element-wise arithmetic, matrix transposition, and dot products.
*   **Aggregation functions** like `sum()`, `mean()`, and `max()`, and how to apply them along specific axes.
*   **Array manipulation techniques** such as `reshape()` and the crucial concept of **broadcasting**, which allows operations between arrays of different shapes under certain conditions.

NumPy's efficiency and extensive functionality make it an indispensable tool for data analysis, machine learning, and scientific research, serving as the bedrock for many other powerful Python libraries.